name: landing-sectur-demo-project

services:
  backend-expressjs:
    container_name: landing-sectur-backend-container
    image: landing-sectur-backend-image:v1.0
    build:
      context: ./backend-sectur
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - "4002:3000"
    networks:
      - nginx-network
      - demo-internal-network

  frontend-reactjs:
    container_name: landing-sectur-frontend-container
    image: landing-sectur-frontend-image:v1.0
    build:
      context: ./frontend-sectur
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_URL_BACKEND=${REACT_APP_URL_BACKEND}
        - REACT_APP_GET_IMG_ARTICULO=${REACT_APP_GET_IMG_ARTICULO}
        - REACT_APP_GET_IMG_HOTEL=${REACT_APP_GET_IMG_HOTEL}
        - REACT_APP_GET_IMG_INFOARTICULO=${REACT_APP_GET_IMG_INFOARTICULO}
    ports:
      - "3004:80"
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
  demo-internal-network:
    external: true