# ... (Etapa de compilación anterior)
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install --force
COPY . .

# Inyectamos la variable durante el build
ARG REACT_APP_URL_BACKEND
ENV REACT_APP_URL_BACKEND=$REACT_APP_URL_BACKEND

ARG REACT_APP_GET_IMG_ARTICULO
ENV REACT_APP_GET_IMG_ARTICULO=$REACT_APP_GET_IMG_ARTICULO

ARG REACT_APP_GET_IMG_HOTEL
ENV REACT_APP_GET_IMG_HOTEL=$REACT_APP_GET_IMG_HOTEL

ARG REACT_APP_GET_IMG_INFOARTICULO
ENV REACT_APP_GET_IMG_INFOARTICULO=$REACT_APP_GET_IMG_INFOARTICULO

RUN npm run build 

# Etapa 2: Nginx
FROM nginx:stable-alpine
# IMPORTANTE: CRA usa la carpeta /build
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]