FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./

# Instalamos solo dependencias de producción (omite devDependencies)
RUN npm install
COPY . .
EXPOSE 3000
CMD ["node", "src/index.js"]